// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgqN_BT65iOeA23gzXmu23JA9l-eYW144',
    appId: '1:813070263886:android:e1e4ab977297b1304ac51f',
    messagingSenderId: '813070263886',
    projectId: 'waifus-pics',
    databaseURL: 'https://waifus-pics-default-rtdb.firebaseio.com',
    storageBucket: 'waifus-pics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO8e4Zomhp1EdQMrGE8imPzeXWWu_y_KE',
    appId: '1:813070263886:ios:12d9501c48e79ac04ac51f',
    messagingSenderId: '813070263886',
    projectId: 'waifus-pics',
    databaseURL: 'https://waifus-pics-default-rtdb.firebaseio.com',
    storageBucket: 'waifus-pics.appspot.com',
    iosClientId: '813070263886-faehkaiv817sfi39ahksptap8so5skgq.apps.googleusercontent.com',
    iosBundleId: 'com.julian.waifupics',
  );
}
